In [1]:
import numpy as np
import torch

In [ ]:
a = np.array([[1,2,3],[4,5,6]])
a[:,-1] = [1,2]
a

array([[1, 2, 1],
       [4, 5, 2]])

In [4]:
Q = 3
SIGMA = 3
A = Q * SIGMA
size = (Q*SIGMA)**2


test = np.zeros((size, size))
for i in range(size):
    test[i, i%A * A: (i%A+1)*A] = [1 if i//A ==j else -1 for j in range(A)]


np.linalg.inv(test)

array([[ 0.42857143,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [-0.07142857, -0.        , -0.        , ..., -0.        ,
        -0.        , -0.        ],
       [-0.07142857, -0.        , -0.        , ..., -0.        ,
        -0.        , -0.        ],
       ...,
       [ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        , -0.07142857],
       [ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        , -0.07142857],
       [ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.42857143]])

In [16]:
for size in range(3,12):
    test = np.eye(size)
    test[test==0] = -1
    print(size, "\n", 2*np.linalg.inv(test))

3 
 [[ 0. -1. -1.]
 [-1. -0. -1.]
 [-1. -1. -0.]]
4 
 [[ 0.5 -0.5 -0.5 -0.5]
 [-0.5  0.5 -0.5 -0.5]
 [-0.5 -0.5  0.5 -0.5]
 [-0.5 -0.5 -0.5  0.5]]
5 
 [[ 0.66666667 -0.33333333 -0.33333333 -0.33333333 -0.33333333]
 [-0.33333333  0.66666667 -0.33333333 -0.33333333 -0.33333333]
 [-0.33333333 -0.33333333  0.66666667 -0.33333333 -0.33333333]
 [-0.33333333 -0.33333333 -0.33333333  0.66666667 -0.33333333]
 [-0.33333333 -0.33333333 -0.33333333 -0.33333333  0.66666667]]
6 
 [[ 0.75 -0.25 -0.25 -0.25 -0.25 -0.25]
 [-0.25  0.75 -0.25 -0.25 -0.25 -0.25]
 [-0.25 -0.25  0.75 -0.25 -0.25 -0.25]
 [-0.25 -0.25 -0.25  0.75 -0.25 -0.25]
 [-0.25 -0.25 -0.25 -0.25  0.75 -0.25]
 [-0.25 -0.25 -0.25 -0.25 -0.25  0.75]]
7 
 [[ 0.8 -0.2 -0.2 -0.2 -0.2 -0.2 -0.2]
 [-0.2  0.8 -0.2 -0.2 -0.2 -0.2 -0.2]
 [-0.2 -0.2  0.8 -0.2 -0.2 -0.2 -0.2]
 [-0.2 -0.2 -0.2  0.8 -0.2 -0.2 -0.2]
 [-0.2 -0.2 -0.2 -0.2  0.8 -0.2 -0.2]
 [-0.2 -0.2 -0.2 -0.2 -0.2  0.8 -0.2]
 [-0.2 -0.2 -0.2 -0.2 -0.2 -0.2  0.8]]
8 
 [[ 0.83333333 -0.16

In [12]:
1/12

0.08333333333333333